// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Basic: typeof import('./components/Basic.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
  }
}

export { }
